src/Sura/Models/Comment.cs
using System;

namespace Sura.Models
{
    public class Comment
    {
        public Guid Id { get; private set; }

        public string Author { get; set; }
        public string AuthorEmail { get; set; }
        public string AuthorUrl { get; set; }

        public string Body { get; set; }

        public DateTimeOffset WrittenAt { get; set; }

        public string UserHostAddress { get; set; }
        public string UserAgent { get; set; }

        public Comment()
        {
            Id = Guid.NewGuid();
            WrittenAt = DateTimeOffset.UtcNow;
        }
    }
}

src/Sura/Areas/Admin/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Raven.Client;
using Raven.Client.Linq;
using Sura.Areas.Admin.Views.Comments.Models;
using Sura.Controllers;
using Sura.Models;
using Sura.Services;

namespace Sura.Areas.Admin.Controllers
{
    [Authorize]
    public class CommentsController : RavenController
    {
        private Settings _settings;

        public CommentsController(IDocumentSession session, ISettingsService settings) : base(session, settings)
        {
            _settings = settings.Load();
        }

        [HttpGet]
        public ActionResult List()
        {
            var comments = Session.Query<PostComments>()
                                        .Customize(x => x.WaitForNonStaleResults())
                                        .ToList();

            ViewBag.AllowComments = _settings.EnableComments;
            ViewBag.CommentsRequireApproval = _settings.CommentsRequireApproval;

            var model = new List<List>();

            foreach (var postComment in comments)
            {
                model.AddRange(postComment.ApprovedComments.Select(comment => new List
                {
                    PostCommentsId = postComment.Id,
                    PostId = postComment.PostId,
                    PostTitle = postComment.PostTitle,
                    PostSlug = postComment.PostSlug,
                    PostPublishedAt = postComment.PostPublishedAt,
                    CommentId = comment.Id,
                    Name = comment.Author,
                    Email = comment.AuthorEmail,
                    Url = comment.AuthorUrl,
                    Body = comment.Body,
                    WrittenAt = comment.WrittenAt,
                    UserHostAddress = comment.UserHostAddress,
                    UserAgent = comment.UserAgent,
                    Approved = true
                }));

                model.AddRange(postComment.UnapprovedComments.Select(comment => new List
                {
                    PostCommentsId = postComment.Id,
                    PostId = postComment.PostId,
                    PostTitle = postComment.PostTitle,
                    PostSlug = postComment.PostSlug,
                    PostPublishedAt = postComment.PostPublishedAt,
                    CommentId = comment.Id,
                    Name = comment.Author,
                    Email = comment.AuthorEmail,
                    Url = comment.AuthorUrl,
                    Body = comment.Body,
                    WrittenAt = comment.WrittenAt,
                    UserHostAddress = comment.UserHostAddress,
                    UserAgent = comment.UserAgent,
                    Approved = false
                }));
            }

            return View(model);
        }
      
        [HttpPost]
        public ActionResult Approve(string slug, Guid commentId)
        {
            var postComments = Session.Query<PostComments>()
                                        .Where(x => x.PostSlug == slug)
                                        .Customize(x => x.Include<PostComments>(y => y.PostId))
                                        .FirstOrDefault();

            if (postComments == null)
                return new HttpStatusCodeResult(404, "Blog post comments not found.");

            var post = Session.Load<Post>(postComments.PostId);

            if (post == null)
                return new HttpStatusCodeResult(404, "Blog post not found.");

            var comment = postComments.UnapprovedComments.FirstOrDefault(c => c.Id == commentId);

            if(comment != null)
            {
                postComments.UnapprovedComments.Remove(comment);
                postComments.ApprovedComments.Add(comment);
            }

            post.NumberOfComments++;

            Session.SaveChanges();

            if (Request.IsAjaxRequest())
                return new HttpStatusCodeResult(200, "Comment approved.");

            return RedirectToAction("List");
        }

        [HttpDelete]
        public ActionResult Reject(string slug, Guid commentId)
        {
            var postComments = Session.Query<PostComments>()
                                        .Where(x => x.PostSlug == slug)
                                        .Customize(x => x.Include<PostComments>(y => y.PostId))
                                        .FirstOrDefault();

            if (postComments == null)
                return new HttpStatusCodeResult(404, "Blog post comments not found.");

            var post = Session.Load<Post>(postComments.PostId);

            if (post == null)
                return new HttpStatusCodeResult(404, "Blog post not found.");

            postComments.UnapprovedComments.RemoveAll(c => c.Id == commentId);

            Session.SaveChanges();

            return new HttpStatusCodeResult(200, "Comment rejected.");
        }

        [HttpDelete]
        public ActionResult Delete(string slug, Guid commentId)
        {
            var postComments = Session.Query<PostComments>()
                                        .Where(x => x.PostSlug == slug)
                                        .Customize(x => x.Include<PostComments>(y => y.PostId))
                                        .FirstOrDefault();

            if (postComments == null)
                return new HttpStatusCodeResult(404, "Blog post comments not found.");

            var post = Session.Load<Post>(postComments.PostId);

            if (post == null)
                return new HttpStatusCodeResult(404, "Blog post not found.");

            postComments.ApprovedComments.RemoveAll(c => c.Id == commentId);

            Session.SaveChanges();

            return new HttpStatusCodeResult(200, "Comment deleted.");
        }
    }
}

src/Sura/Areas/Admin/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Raven.Client;
using Sura.Areas.Admin.Infrastructure;
using Sura.Areas.Admin.Views.Settings.Models;
using Sura.Controllers;
using Sura.Models;
using Sura.Services;

namespace Sura.Areas.Admin.Controllers
{
    [Authorize]
    public class SettingsController : RavenController
    {
        public SettingsController(IDocumentSession session, ISettingsService service) : base(session, service)
        {
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var settings = Settings.Load();

            return View(Mapper.Map<Settings, Edit>(settings));
        }

        [HttpPost]
        public ActionResult Edit(Edit model)
        {
            var settings = new Settings
                               {
                                   KeepUsersOnlineFor = model.KeepUsersOnlineFor,
                                   EnableComments =  model.EnableComments == Status.Enabled,
                                   CommentsRequireApproval = model.CommentsRequireApproval == Status.Enabled
                               };

            Settings.Save(settings);
            ViewBag.Success = true;

            return View(Mapper.Map<Settings, Edit>(settings));
        }
    }
}

src/Sura/Controllers/BlogController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using Raven.Client;
using Raven.Client.Linq;
using Sura.Models;
using Sura.Services;

namespace Sura.Controllers
{
    public class BlogController : RavenController
    {
        public BlogController(IDocumentSession session, ISettingsService service) : base(session, service)
        {
        }
        
        [HttpGet]
        public ActionResult List()
        {
            var posts = Session.Query<Post>()
                               .Where(x => x.PublishedAt != null &&
                                            x.TrashedAt == null &&
                                            x.PublishedAt <= DateTimeOffset.Now)
                               .OrderByDescending(x => x.PublishedAt)
                               .ToList();

            return View(Mapper.Map<IEnumerable<Post>, IEnumerable<Sura.Views.Blog.Models.Post>>(posts));
        }

        [HttpGet]
        public ActionResult Post(string slug, bool posted = false, bool moderation = false)
        {
            var comments = Session.Query<PostComments>()
                                  .Include(p => p.PostId)
                                  .Where(x => x.PostSlug == slug)
                                  .FirstOrDefault();

            Post post;
            if (comments == null)
                post = Session.Query<Post>().Where(x => x.Slug == slug).FirstOrDefault();
            else
                post = Session.Load<Post>(comments.PostId);

            if (post == null)
                return new HttpStatusCodeResult(404, "We're having trouble finding that post right now.");

            var model = Mapper.Map<Post, Sura.Views.Blog.Models.Post>(post);
            model.Comments = comments.ApprovedComments.Select(
                comment => new Views.Blog.Models.Comment()
                               {
                                   Name = comment.Author,
                                   Email = comment.AuthorEmail,
                                   Url = comment.AuthorUrl,
                                   Body = comment.Body,
                                   WrittenAt = comment.WrittenAt
                               });

            ViewBag.Posted = posted;
            ViewBag.AwaitingModeration = moderation;
            
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Comment(Views.Blog.Models.Comment model)
        {
            if (string.IsNullOrWhiteSpace(model.Name))
                ModelState.AddModelError("Required", "You must enter your name.");

            if (string.IsNullOrWhiteSpace(model.Email))
                ModelState.AddModelError("Required", "You must enter an email address. Your email will not be publicly viewable.");

            if (string.IsNullOrWhiteSpace(model.Body))
                ModelState.AddModelError("Required", "You must some content for your comment.");

            var comments = Session.Query<PostComments>()
                                  .Include(x => x.PostId)
                                  .Where(x => x.PostId == model.PostId)
                                  .FirstOrDefault();

            if (comments == null)
                return new HttpStatusCodeResult(404, "We're having trouble loading the comments for that post.");

            var post = Session.Load<Post>(comments.PostId);

            if (post == null)
                return new HttpStatusCodeResult(404, "We're having trouble finding that post right now.");

            if (ModelState.IsValid == false)
                return RedirectToAction("Post", new { slug = post.Slug });

            if (post.TrashedAt != null || post.PublishedAt == null || post.PublishedAt.Value > DateTimeOffset.UtcNow)
                return new HttpStatusCodeResult(403, "You aren't allowed post a comment on this post right now.");


            var comment = new Comment
            {
                Author = model.Name,
                AuthorEmail = model.Email,
                AuthorUrl = model.Url,
                Body = model.Body,
                WrittenAt = DateTimeOffset.UtcNow,
                UserHostAddress = Request.UserHostAddress,
                UserAgent = Request.UserAgent
            };

            var settings = Settings.Load();
            var posted = false;
            var moderation = false;

            if (settings.CommentsRequireApproval == false)
            {
                comments.ApprovedComments.Add(comment);
                post.NumberOfComments++;
                posted = true;
            }
            else
            {
                comments.UnapprovedComments.Add(comment);
                moderation = true;
            }

            Session.SaveChanges();
            return RedirectToAction("Post", new { slug = post.Slug, posted, moderation });
        }

        [HttpGet]
        public ActionResult Tag(string tag)
        {
            var posts = Session.Query<Post>()
                                .Where(x => x.PublishedAt != null &&
                                            x.TrashedAt == null &&
                                            x.PublishedAt <= DateTimeOffset.Now &&
                                            x.Tags.Any(y => y == tag.ToLower()))
                                .OrderByDescending(x => x.PublishedAt)
                                .ToList();

            if (posts.Count == 0)
                return new HttpStatusCodeResult(404, string.Format("No posts are tagged with the tag '{0}'.", tag));

            ViewBag.Tag = tag;

            return View(Mapper.Map<IEnumerable<Post>, IEnumerable<Sura.Views.Blog.Models.Post>>(posts));
        }


        [HttpGet]
        public ActionResult Archive(int year, int? month, int? day)
        {
            var posts = Session.Query<Post>()
                                   .Where(x => x.PublishedAt != null &&
                                               x.TrashedAt == null &&
                                               x.PublishedAt <= DateTimeOffset.Now)
                                   .OrderByDescending(x => x.PublishedAt)
                                   .ToList();

            posts = posts.Where(post => post.PublishedAt.Value.Year == year).ToList();
            ViewBag.Year = year;

            if (month != null)
            {
                posts = posts.Where(post => post.PublishedAt.Value.Month == month.Value).ToList();
                ViewBag.Month = month.Value < 10 ? "0" + month.Value : month.Value.ToString();
            }

            if (day != null)
            {
                posts = posts.Where(post => post.PublishedAt.Value.Day == day.Value).ToList();
                ViewBag.Day = day.Value < 10 ? "0" + day.Value : day.ToString();
            }

            return View(Mapper.Map<IEnumerable<Post>, IEnumerable<Sura.Views.Blog.Models.Post>>(posts));
        }
    }
}

src/Sura/Areas/Admin/Views/Comments/List.cshtml
@using Sura.Areas.Admin.Views.Comments.Models
@model IEnumerable<List>
@{
    ViewBag.Title = "Comments";
    var unapproved = Model.Where(x => x.Approved == false).Count();
}
@section breadcrumbs
{
<li class="active"><span class="divider">/</span> @Html.ActionLink("Comments", "List", "Comments")</li>
}
<section class="span12">
  <h1>Comments</h1>

@if (ViewBag.AllowComments == false)
{
  <div class="alert">
    <a data-dismiss="alert" class="close">×</a>
    Comments are currently disabled throughout the blog. @Html.ActionLink("Change this setting", "Edit", "Settings")
  </div>
}

@if (ViewBag.CommentsRequireApproval == false)
{
  <div class="alert">
    <a data-dismiss="alert" class="close">×</a>
    Comments are not currently moderated. New comments will viewable to the public. @Html.ActionLink("Change this setting", "Edit", "Settings")
  </div>
}

<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#unapproved" data-toggle="tab">Awaiting Moderation 
    @if (unapproved > 0)
    { 
        @:(@unapproved) 
    }
    </a></li>
    <li><a href="#approved" data-toggle="tab">Approved</a></li>
  </ul>
  <div class="tab-content">
    <table id="unapproved" class="tab-pane table table-striped active">
       <thead>
                <tr>
                    <th>Post</th>
                    <th>Post Published At</th>
                    <th>Author</th>
                    <th>Email</th>
                    <th>Comment</th>
                    <th>Submitted</th>
                </tr>
            </thead>
            <tbody> @foreach (var comment in Model.Where(x => x.Approved == false).OrderBy(x => x.WrittenAt).OrderBy(x => x.PostPublishedAt))
                    {
                 <tr>
                    <td>@Html.RouteLink(@comment.PostTitle, "Blog_Post", new { slug = @comment.PostSlug }, null)</td>
                    <td>@comment.PostPublishedAt.ToString("dd/MM/yy HH:mm")</td>
                    @if (string.IsNullOrWhiteSpace(comment.Url) == false)
                    {
                         <td><a href="@comment.Url">@comment.Name</a></td>
                    }
                    else
                    {
                        <td>@comment.Name</td>
                    }            
                    <td>@comment.Email</td>
                    <td>@comment.Body</td>
                    <td>@comment.WrittenAt</td>
                    <td>@Ajax.ActionLink("Approve", "Approve", "Comments", new { slug = comment.PostSlug, commentId = comment.CommentId },
                                new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    Confirm = "Are you sure you want to approve this comment?",
                                    OnSuccess = "redirect('" + @Url.Action("List", "Comments") + "')"
                                })
                    </td>
                    <td>@Ajax.ActionLink("Reject", "Reject", "Comments", new { slug = comment.PostSlug, commentId = comment.CommentId },
                                new AjaxOptions
                                {
                                    HttpMethod = "DELETE",
                                    Confirm = "Are you sure you want to reject this comment? It will be permanently deleted.",
                                    OnSuccess = "redirect('" + @Url.Action("List", "Comments") + "')"
                                })
                    </td>
                </tr> }
            </tbody>            
        </table>  

    <table id="approved" class="tab-pane table table-striped">    
      <thead>
        <tr>
          <th>Post</th>
          <th>Post Published At</th>
          <th>Author</th>
          <th>Comment</th>
          <th>Submitted</th>
        </tr>
      </thead>
      <tbody> 
@foreach (var comment in Model.Where(x => x.Approved).OrderBy(x => x.WrittenAt).OrderBy(x => x.PostPublishedAt))
{       <tr>
          <td>@Html.ActionLink(@comment.PostTitle, "Post", "Blog", new { slug = @comment.PostSlug }, null)</td>
          <td>@comment.PostPublishedAt.ToString("dd/MM/yy HH:mm")</td>
  @if (string.IsNullOrWhiteSpace(comment.Url) == false)
  {
          <td><a href="@comment.Url">@comment.Name</a></td>
  }
  else
  {
          <td>@comment.Name</td>
  }
          <td>@comment.Body</td>
          <td>@comment.WrittenAt</td>
          <td>@Ajax.ActionLink("Delete", "Delete", "Comments", new { slug = comment.PostSlug, commentId = comment.CommentId },
            new AjaxOptions
            {
                HttpMethod = "DELETE",
                Confirm = "Are you sure you want to permanently delete this comment?",
                OnSuccess = "redirect('" + @Url.Action("List", "Comments") + "')"
            })</td>
        </tr> 
}
      </tbody>            
    </table>
  </div>
</div>

</section>